# Generated by Django 4.2.7 on 2024-02-15 14:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "year_of_release",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(
                                music.models.get_current_year
                            ),
                        ]
                    ),
                ),
                (
                    "produced_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "first_appearance",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(
                                music.models.get_current_year
                            ),
                        ],
                        verbose_name="Year of first appearance",
                    ),
                ),
                (
                    "last_appearance",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(
                                music.models.get_current_year
                            ),
                        ],
                        verbose_name="Year of last appearance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio")),
                ("title", models.CharField(max_length=250)),
                ("duration", models.DurationField()),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Indie", "Indie"),
                            ("Pop", "Pop"),
                            ("Rock", "Rock"),
                            ("Funky", "Funky"),
                            ("Reggaeton", "Reggaeton"),
                            ("Classic", "Classic"),
                            ("Orquestra", "Orquestra"),
                            ("Folk", "Folk"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("playbacks", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        validators=[music.models.less_than_five],
                    ),
                ),
                ("deal_of_the_day", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        max_length=250,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.album",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_start_time", models.TimeField(default=music.models.nine_pm)),
                (
                    "daily_finish_time",
                    models.TimeField(default=music.models.fourteen_pm),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("Indie", "Indie"),
                            ("Pop", "Pop"),
                            ("Rock", "Rock"),
                            ("Funky", "Funky"),
                            ("Reggaeton", "Reggaeton"),
                            ("Classic", "Classic"),
                            ("Orquestra", "Orquestra"),
                            ("Folk", "Folk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_song",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.song",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("nationality", models.CharField(max_length=2)),
                (
                    "instrument",
                    models.CharField(
                        choices=[
                            ("piano", "Piano"),
                            ("eguitar", "Electric Guitar"),
                            ("cguitar", "Classical Guitar"),
                            ("aguitar", "Acoustic Guitar"),
                            ("ebass", "Electric Bass"),
                            ("bass", "Bass"),
                            ("drums", "Drums"),
                            ("voice", "Voice"),
                            ("violin", "Violin"),
                            ("harp", "Harp"),
                            ("handpan", "Handpan"),
                            ("tambourine", "Tambourine"),
                            ("sax", "Saxophone"),
                            ("trumpet", "Trumpet"),
                            ("trombone", "Trombone"),
                            ("flute", "Flute"),
                            ("clarinet", "Clarinet"),
                            ("ukulele", "Ukulele"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="music.author",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                fields=("title", "author", "album", "duration"), name="unique_song"
            ),
        ),
    ]
